default: &default

  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: DevOpsOne_development

test:
  <<: *default
  database: DevOpsOne_test

production:
  <<: *default
  database: DevOpsOne_production
  password: <%= ENV['DEVOPSONE_DATABASE_PASSWORD'] %>
